sudo update-alternatives --auto gcc
sudo update-alternatives --auto g++
sudo update-alternatives --auto cpp
sudo update-alternatives --auto gcc-ar
sudo update-alternatives --auto gcc-nm
sudo update-alternatives --auto gcc-ranlib
sudo update-alternatives --auto gcc-nm
sudo update-alternatives --auto gcov
sudo update-alternatives --auto gcov-dump
sudo update-alternatives --auto gcov-tool
sudo update-alternatives --auto x86_64-linux-gnu-gfortran
sudo update-alternatives --auto x86_64-linux-gnu-gcov
sudo update-alternatives --auto x86_64-linux-gnu-gcov-tool
sudo update-alternatives --auto x86_64-linux-gnu-gcov-dump
sudo update-alternatives --auto x86_64-linux-gnu-gcc-ranlib
sudo update-alternatives --auto x86_64-linux-gnu-gcc-ar
sudo update-alternatives --auto x86_64-linux-gnu-gcc
sudo update-alternatives --auto x86_64-linux-gnu-g++
sudo update-alternatives --auto x86_64-linux-gnu-cpp

